version: '3'

services:
  gsmaps:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - OMNIVERSE_SERVER_IP=172.28.33.205
      - OMNIVERSE_SIGNALING_PORT=49100
      - OMNIVERSE_MEDIA_PORT=1024
      - OMNIVERSE_STREAM_SOURCE=direct
    restart: unless-stopped